import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import itemsRouter from "./items";
import stockRouter from "./stock";
import purchasesRouter from "./purchases";
import salesRouter from "./sales";
import vendorsRouter from "./vendors";
import customersRouter from "./customers";
import payablesRouter from "./payables";
import receivablesRouter from "./receivables";
import expensesRouter from "./expenses";
import balancesRouter from "./balances";
import usersRouter from "./users";
import reportsRouter from "./reports";
import dashboardRouter from "./dashboard";
import loansRouter from "./loans";
import backupRouter from "./backup";
import adminRouter from "./admin";
import serialNumbersRouter from "./serial-numbers";
import analyticsRouter from "./analytics";
import colorsRouter from "./colors";
import staffRouter from "./staff";
import creditRouter from "./credit";
import receiptsRouter from "./receipts";
import repairsRouter from "./repairs";
import publicRouter from "./public";
import announcementsRouter from "./announcements";
import notificationsRouter from "./notifications";
import stockCountRouter from "./stock-count";
import receiptScannerRouter from "./receipt-scanner";
import usageAnalyticsRouter from "./usage-analytics";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(itemsRouter);
router.use(stockRouter);
router.use(purchasesRouter);
router.use(salesRouter);
router.use(vendorsRouter);
router.use(customersRouter);
router.use(payablesRouter);
router.use(receivablesRouter);
router.use(loansRouter);
router.use(expensesRouter);
router.use(balancesRouter);
router.use(usersRouter);
router.use(reportsRouter);
router.use(dashboardRouter);
router.use(backupRouter);
router.use(adminRouter);
router.use(serialNumbersRouter);
router.use(analyticsRouter);
router.use(colorsRouter);
router.use(staffRouter);
router.use(creditRouter);
router.use(receiptsRouter);
router.use(repairsRouter);
router.use(publicRouter);
router.use(announcementsRouter);
router.use(notificationsRouter);
router.use(stockCountRouter);
router.use(receiptScannerRouter);
router.use(usageAnalyticsRouter);

export default router;
